Resources:
  ELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ecs-elb
      Scheme: internet-facing
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: 30
      Subnets:
        - Fn::ImportValue:
            Fn::Sub:
              "${NetworkStackName}-PublicSubnetAz1"
        - Fn::ImportValue:
            Fn::Sub:
              "${NetworkStackName}-PublicSubnetAz2"
      SecurityGroups:
        - Ref: PublicSecurityGroup
  ELBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: ELBServiceRole
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: ELBTargetGroup
      LoadBalancerArn:
        Ref: ELB
      Port: '80'
      Protocol: HTTP
  ELBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ELB
    Properties:
      Name: ELBTargetGroup
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcID"
  ELBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    DependsOn: ELBListener
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn:
          Ref: ELBTargetGroup
      Conditions:
      - Field: path-pattern
        Values: [/]
      ListenerArn:
        Ref:
          ELBListener
      Priority: 1
