service: serverlecs-dev

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-2

plugins:
  - serverlecs-plugin

# functions:
#   hello:
#     handler: handler.hello

custom:
  serverlecs:
    service:
      cluster: arn:aws:ecs:ap-southeast-2:005213230316:cluster/vtha-ECSCluster-11NSGX52FXRSZ
      repository: 005213230316.dkr.ecr.ap-southeast-2.amazonaws.com/serverlecs
      containers:
        hello:
          srcPath: src
          path: /hello
          memory: 128
    # blah:
    #   cluster: ClusterID
    #   repository: 005213230316.dkr.ecr.ap-southeast-2.amazonaws.com/serverlecs
    #   containers:
    #     hello:
    #       src: handler.hello
    #       memory: 128
