service: serverlecs-dev

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-2

plugins:
  - serverlecs-plugin

# functions:
#   hello:
#     handler: handler.hello

custom:
  containerless:
    cluster:
      instance_type: t2.small
      subnets:
        - subnet-12359e64
        - subnet-b442c0d0
        - subnet-a2b967fb
    repository: 005213230316.dkr.ecr.ap-southeast-2.amazonaws.com/serverlecs
    vpcId:
      Fn::ImportValue: triple-az-vpc-VpcID
    # clusterId: arn:aws:ecs:ap-southeast-2:005213230316:cluster/vtha-ECSCluster-1A5ZYNUN7X46N
    # load_balancer:
    #   security_group:
    #     Fn::ImportValue: vtha-SecurityGroup
    #   subnets:
    #     - Fn::ImportValue: triple-az-vpc-PublicSubnetAz1
    #     - Fn::ImportValue: triple-az-vpc-PublicSubnetAz2
    #     - Fn::ImportValue: triple-az-vpc-PublicSubnetAz3
    applications:
      hello-1:
        srcPath: src-1
        urlPath: /
        port: 3000
        memory: 128
      hello-2:
        srcPath: src-2
        urlPath: /hello
        port: 3000
        memory: 128
      hello-3:
        srcPath: src-2
        memory: 128
      # hello-2:
      #   srcPath: src-2
      #   memory: 128

          # port: 3000

      # load_balancer:
      #   targetGroupArn:
      #   securityGroup:
      #
      # logRetention: 14
      # DesiredCount: 1

    # blah:
    #   cluster: ClusterID
    #   repository: 005213230316.dkr.ecr.ap-southeast-2.amazonaws.com/serverlecs
    #   containers:
    #     hello:
    #       src: handler.hello
    #       memory: 128
