Parameters:
  VPCId:
    Description: Name of the stack containing a VPC with at least two subnets
    Type: AWS::EC2::VPC::Id
  VPCZoneIdentifier:
    Description: Name of the stack containing a VPC with at least two subnets
    Type: CommaDelimitedList
Resources:
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    # DependsOn: ECSCluster
    Properties:
      VPCZoneIdentifier:
        Ref: VPCZoneIdentifier
        # - Fn::ImportValue:
        #     Fn::Sub:
        #       "${NetworkStackName}-PublicSubnetAz1"
      LaunchConfigurationName:
        Ref: LaunchConfiguration
      MinSize: '1'
      MaxSize:
        Ref: 'MaxSize'
      DesiredCapacity:
        Ref: 'DesiredCapacity'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT60M
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: 'true'
        PauseTime: PT60S
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId:
        Fn::FindInMap: [AWSRegionToAMI, Ref: 'AWS::Region', AMIID]
      SecurityGroups:
        - Ref: PublicSecurityGroup
      InstanceType:
        Ref: InstanceType
      IamInstanceProfile:
        Ref: EC2InstanceProfile
      KeyName: ecs-instance
      UserData:
        Fn::Base64:
          Fn::Sub: (( file "includes/instance-user-data.sh" ))
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: ECSInstanceRole
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS Public Security Group
      VpcId:
        Ref: VPCId
  PublicSecurityGroupDynamicPorts:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: PublicSecurityGroup
      IpProtocol: tcp
      FromPort: 31000
      ToPort: 61000
      SourceSecurityGroupId:
        Ref: PublicSecurityGroup
  PublicSecurityGroupHTTPInbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: PublicSecurityGroup
      IpProtocol: tcp
      FromPort: '80'
      ToPort: '80'
      CidrIp: 0.0.0.0/0
  PublicSecurityGroupHTTPSInbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: PublicSecurityGroup
      IpProtocol: tcp
      FromPort: '443'
      ToPort: '443'
      CidrIp: 0.0.0.0/0
  PublicSecurityGroupSSHInbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: PublicSecurityGroup
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
