AWSTemplateFormatVersion: "2010-09-09"
Description: "Test Docker deployment"
Parameters:
Mappings:
  # ECS Optimzied AMIs http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html
  # Marketplace: https://aws.amazon.com/marketplace/pp/B00U6QTYI2?ref=cns_srchrow
  AWSRegionToAMI:
    us-east-1:
      AMIID: ami-6df8fe7a
    us-east-2:
      AMIID: ami-c6b5efa3
    us-west-1:
      AMIID: ami-1eda8d7e
    us-west-2:
      AMIID: ami-a2ca61c2
    eu-west-1:
      AMIID: ami-ba346ec9
    eu-west-2:
      AMIID: ami-42c5cf26
    eu-central-1:
      AMIID: ami-e012d48f
    ap-northeast-1:
      AMIID: ami-08f7956f
    ap-southeast-1:
      AMIID: ami-f4832f97
    ap-southeast-2:
      AMIID: ami-774b7314
    ca-central-1:
      AMIID: ami-be45f7da
Resources:
Outputs:
