Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
Outputs:
  ClusterID:
    Description: ClusterID
    Value:
      Ref: ECSCluster
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-ClusterID"
